"""add last posted number to channels

Revision ID: 167b96c69403
Revises: 5fdfc968c434
Create Date: 2025-07-06 22:03:05.663816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167b96c69403'
down_revision: Union[str, None] = '5fdfc968c434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('last_posted_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'last_posted_number')
    # ### end Alembic commands ###
