"""relocated post settings to the channels table

Revision ID: 50324fe18764
Revises: 9496b57c2833
Create Date: 2025-07-06 20:24:51.766928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50324fe18764'
down_revision: Union[str, None] = '9496b57c2833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('interval', sa.Integer(), nullable=False))
    op.add_column('channels', sa.Column('sent', sa.Integer(), nullable=False))
    op.add_column('channels', sa.Column('limit', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('status', sa.Enum('WORKING', 'STOPPED', name='status'), nullable=False))
    op.drop_column('posts', 'interval')
    op.drop_column('posts', 'sent')
    op.drop_column('posts', 'limit')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'last_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_message_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('status', mysql.ENUM('WORKING', 'STOPPED'), nullable=False))
    op.add_column('posts', sa.Column('limit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('sent', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('interval', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('channels', 'status')
    op.drop_column('channels', 'last_message_id')
    op.drop_column('channels', 'limit')
    op.drop_column('channels', 'sent')
    op.drop_column('channels', 'interval')
    # ### end Alembic commands ###
