"""add last_message_id column to posts

Revision ID: 8cbaada5e6d4
Revises: fb19df15d78d
Create Date: 2025-07-06 18:41:34.658333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbaada5e6d4'
down_revision: Union[str, None] = 'fb19df15d78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'last_message_id')
    # ### end Alembic commands ###
