"""delete status from channels table

Revision ID: 9496b57c2833
Revises: 8cbaada5e6d4
Create Date: 2025-07-06 18:55:57.145626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9496b57c2833'
down_revision: Union[str, None] = '8cbaada5e6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('status', mysql.ENUM('WORKING', 'STOPPED'), nullable=False))
    # ### end Alembic commands ###
